### ISSUE TITLE
Отсутствует часть значений в PaymentSubjectTypeEnum

### ISSUE THREAD

**Issue by PavelRyazanov** [orangedata-official/CSSharp-OrangeData-official#8]
В `PaymentSubjectTypeEnum` не хватает значений под:

> 14 – Имущественное право
> 15 – Внереализационный доход*
> 16 – Страховые взносы*
> 17 - Торговый сбор
> 18 - Курортный сбор
> 19 – Залог
> 
Которые есть в Протоколе взаимодействия с интернет кассой

**Comment by lebedevat** [comment]
Добавлено [MR](https://github.com/orangedata-official/CSSharp-OrangeData-official/pull/9)
